export const departmentOptions = [
  { label: "Agricultural Engineering", value: "Agricultural Engineering" , code:"AGRI"},
  { label: "Artificial Intelligence and Data Science", value: "Artificial Intelligence and Data Science" , code:"AIDS"},
  { label: "Artificial Intelligence and Machine Learning", value: "Artificial Intelligence and Machine Learning" , code:"AIML"},
  { label: "Biomedical Engineering", value: "Biomedical Engineering" , code:"BIO"},
  { label: "Biotechnology", value: "Biotechnology" , code:"BIOTECH"},
  { label: "Civil Engineering", value: "Civil Engineering" , code:"CIVIL"},
  { label: "Computer Science & Business Systems", value: "Computer Science & Business Systems" , code:"CSBS"},
  { label: "Computer Science & Design", value: "Computer Science & Design" , code:"CSD"},
  { label: "Computer Science & Engineering", value: "Computer Science & Engineering" , code:"CSE"},
  { label: "Computer Technology", value: "Computer Technology" , code:"CT"},
  { label: "Electrical & Electronics Engineering", value: "Electrical & Electronics Engineering" , code:"EEE"},
  { label: "Electronics & Communication Engineering", value: "Electronics & Communication Engineering" , code:"ECE"},
  { label: "Electronics & Instrumentation Engineering", value: "Electronics & Instrumentation Engineering" , code:"E&I"},
  { label: "Fashion Technology", value: "Fashion Technology" , code:"FT"},
  { label: "Food Technology", value: "Food Technology" , code:"Food TECH"},
  { label: "Information Science & Engineering", value: "Information Science & Engineering" , code:"ISE"},
  { label: "Information Technology", value: "Information Technology" , code:"IT"},
  { label: "Mechanical Engineering", value: "Mechanical Engineering" , code:"MECH"},
  { label: "Mechatronics Engineering", value: "Mechatronics Engineering" , code:"MZ"},
  { label: "Textile Technology", value: "Textile Technology" , code:"TEXTILE"}
];
